name: CommandSync
main: Mr_Krab.CommandSyncClient.Bukkit.CSC
version: 2.5
author: YoFuzzy3
description: Synchronize commands across servers.

commands:
  sync:
    description: Synchronize commands across servers.
    
permissions:
  sync.use:
    description: Access to /sync.
    default: op